// <auto-generated />
using System;
using ImpactAPI.Tenders.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImpactAPI.Tenders.Database.Migrations
{
    [DbContext(typeof(TendersDbContext))]
    [Migration("20250611195848_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ImpactAPI.Tenders.Database.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("ImpactAPI.Tenders.Database.Tender", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("AwardedValueInEuro")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AwardedValueInEuro");

                    b.HasIndex("Date");

                    b.ToTable("Tenders");
                });

            modelBuilder.Entity("SupplierTender", b =>
                {
                    b.Property<int>("SuppliersId")
                        .HasColumnType("int");

                    b.Property<string>("TendersId")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("SuppliersId", "TendersId");

                    b.HasIndex("TendersId");

                    b.ToTable("SupplierTender");
                });

            modelBuilder.Entity("SupplierTender", b =>
                {
                    b.HasOne("ImpactAPI.Tenders.Database.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SuppliersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImpactAPI.Tenders.Database.Tender", null)
                        .WithMany()
                        .HasForeignKey("TendersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
